#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=2000
spring:
  application:
    name: ribbon-consumer
    
server:
  port: 9003
  
eureka:
  client:
    service-url:
      defaultZone: http://lumione:1111/eureka/,http://lumitwo:1112/eureka/
      
