server:
  port: 9102
  
eureka:
  client:
    service-url:
      defaultZone: http://lumiseven:1117/eureka/
      
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    
spring:
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411