spring: 
  application: 
    name: eureka-server

server: 
  port: 1111
  
eureka: 
  instance: 
    hostname: lumione
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://lumitwo:1112/eureka/